In [1]:
import pandas as pd

In [3]:
data_1 = pd.read_csv("crop_production.csv")
data_1

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0
...,...,...,...,...,...,...,...
246086,West Bengal,PURULIA,2014,Summer,Rice,306.0,801.0
246087,West Bengal,PURULIA,2014,Summer,Sesamum,627.0,463.0
246088,West Bengal,PURULIA,2014,Whole Year,Sugarcane,324.0,16250.0
246089,West Bengal,PURULIA,2014,Winter,Rice,279151.0,597899.0
246090,West Bengal,PURULIA,2014,Winter,Sesamum,175.0,88.0

KeyError: "None of [Index(['Andaman and Nicobar Islands', 'Andaman and Nicobar Islands',\n       'Andaman and Nicobar Islands', 'Andaman and Nicobar Islands',\n       'Andaman and Nicobar Islands', 'Andaman and Nicobar Islands',\n       'Andaman and Nicobar Islands', 'Andaman and Nicobar Islands',\n       'Andaman and Nicobar Islands', 'Andaman and Nicobar Islands',\n       ...\n       'West Bengal', 'West Bengal', 'West Bengal', 'West Bengal',\n       'West Bengal', 'West Bengal', 'West Bengal', 'West Bengal',\n       'West Bengal', 'West Bengal'],\n      dtype='object', length=246091)] are in the [columns]"